name: Deploy Laravel Application

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, pdo, zip, bcmath, xml, curl, gd

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libpng-dev \
            libjpeg-dev \
            libfreetype6-dev \
            php-gd
          composer install --prefer-dist \
            --no-ansi \
            --no-interaction \
            --no-scripts \
            --no-progress \
            --no-suggest

      - name: Copy .env file
        run: cp .env.example .env

      - name: Generate application key
        run: php artisan key:generate

      - name: Setup testing environment
        run: cp .env.testing .env
        env:
          APP_ENV: testing

      - name: Cache configuration
        run: |
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

      - name: Run tests
        run: php artisan test
        env:
          APP_ENV: testing

      - name: Start Laravel application
        run: php artisan serve --host=0.0.0.0 --port=8000 &
        env:
          APP_ENV: local

      - name: Wait for application to start
        run: sleep 10

      - name: Test if application is running
        run: curl --fail http://127.0.0.1:8000 || true
