name: Deploy Laravel Application

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, pdo, zip, bcmath, xml, curl, gd

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libpng-dev libjpeg-dev libfreetype6-dev
          sudo apt-get install -y php-gd
          composer install --prefer-dist --no-ansi --no-interaction --no-scripts --no-progress --no-suggest

      - name: Copy .env file
        run: cp .env.example .env

      - name: Generate application key
        run: php artisan key:generate

      # Ignore the migration step
      #- name: Run migrations
      #  run: php artisan migrate --force

      - name: Cache configuration
        run: |
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

      - name: Run tests
        run: |
          cp .env.testing .env  # Copie du fichier .env de test
          php artisan test
        env:
          APP_ENV: testing

      - name: Run Laravel application
        run: php artisan serve --host=0.0.0.0 --port=8000
