name: Deploy Laravel Application

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, pdo, zip, bcmath, xml, curl, gd

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libpng-dev libjpeg-dev libfreetype6-dev
          sudo apt-get install -y php-gd
          composer install --prefer-dist --no-ansi --no-interaction --no-scripts --no-progress --no-suggest

      - name: Copy .env file
        run: cp .env.example .env

      - name: Generate application key
        run: php artisan key:generate

      - name: Setup testing environment
        run: cp .env.testing .env  # Copie du fichier .env de test
        env:
          APP_ENV: testing

      - name: Cache configuration
        run: |
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

      - name: Stop Apache if running
        run: sudo service apache2 stop || true

      - name: Copy files to Apache directory
        run: |
          sudo rm -rf /var/www/html/*
          sudo cp -R * /var/www/html/
          sudo chown -R www-data:www-data /var/www/html/

      - name: Restart Apache
        run: sudo service apache2 restart

      - name: Wait for deployment to complete
        run: sleep 10

      - name: Test if application is running
        run: curl --fail http://localhost || true
