name: Deploy Laravel Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libpng-dev libjpeg-dev libfreetype6-dev
          docker-php-ext-configure gd --with-freetype --with-jpeg
          docker-php-ext-install gd
          composer install --prefer-dist --no-ansi --no-interaction --no-scripts --no-progress --no-suggest


      - name: Copy .env file
        run: |
          cp .env.example .env
        env:
          APP_ENV: testing
          APP_DEBUG: true
          APP_KEY: base64:yourbase64keyhere
          DB_CONNECTION: sqlite
          DB_DATABASE: :memory

      - name: Generate application key
        run: php artisan key:generate

      - name: Run migrations
        run: php artisan migrate --force

      - name: Cache configuration
        run: |
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

      - name: Run tests
        run: php artisan test

      - name: Run Laravel application
        run: php artisan serve --host=0.0.0.0 --port=8000
